import sqlite3


class Database:
    """
    So far, I've outlined functions in here according to this schema:
    Student-table: pitt id, discord id
    courses table: canvas course id, name, associated category of channels, and a message id for people to add reactions to
    recitations table: course table foreign key, recitation name (indicating time probably), reaction id for its role and the role id

    I don't remember if there was more that we talked about when sketching the db schema, probably.
    """
    def __init__(self, db_filename):
        self.conn = sqlite3.connect(db_filename)
        self.conn.execute("PRAGMA foreign_keys = ON;")
        self.init_db()

    # Initializes the DB schema
    def init_db(self):
        cursor = self.conn.cursor()

        # Links Pitt ID with a Discord ID
        cursor.execute("""CREATE TABLE IF NOT EXISTS students(
                       pitt_id TEXT PRIMARY KEY NOT NULL,
                       discord_id INTEGER NOT NULL)""")
        
        # Inherently will use ROWID as a PK, autogenerated by SQLite
        cursor.execute("""CREATE TABLE IF NOT EXISTS admin(
                       name TEXT NOT NULL, 
                       server_id INTEGER NOT NULL, 
                       discord_id INTEGER UNIQUE NOT NULL,
                       FOREIGN KEY (discord_id) REFERENCES students(discord_id))""")
        
       # Can also use ROWID
        cursor.execute("""CREATE TABLE IF NOT EXISTS course(
                       course_number INTEGER PRIMARY KEY NOT NULL,
                       course_canvas_id INTEGER UNIQUE NOT NULL, 
                       course_name TEXT NOT NULL, 
                       category_channel_id INTEGER NOT NULL, 
                       recitation_react_message_id INTEGER NOT NULL, 
                       student_role_id INTEGER NOT NULL, 
                       ta_role_id INTEGER NOT NULL,
                       course_admin INTEGER,
                       FOREIGN KEY (course_admin) REFERENCES admin(ROWID)
                       ON DELETE CASCADE)""")
        
        # Can make recitation_id an implicit PK using ROWID if we would like
        cursor.execute("""CREATE TABLE IF NOT EXISTS recitation(
                       recitation_id INTEGER PRIMARY KEY,
                       course_number INTEGER NOT NULL,
                       recitation_name TEXT NOT NULL, 
                       reaction_id INTEGER NOT NULL, 
                       associated_role_id INTEGER NOT NULL, 
                       FOREIGN KEY (course_number) REFERENCES course(course_number)
                       ON DELETE CASCADE)""")
        
        cursor.execute("""CREATE TABLE IF NOT EXISTS messages(
                       message_id TEXT PRIMARY KEY NOT NULL, 
                       message_time TEXT NOT NULL)""")

    # Adds a user to the admin table
    def add_admin(self, name, server_id, discord_id):
        cursor = self.conn.cursor()

        cursor.execute("INSERT INTO admin VALUES (?, ?, ?)", (name, server_id, discord_id,))
        
        self.conn.commit()

    # Passing in the integer of an associated admin removes a user from the admin table, using ROWID as a PK
    def remove_admin(self, discord_id):
        cursor = self.conn.cursor()

        cursor.execute("DELETE FROM admin WHERE discord_id = (?)", (discord_id,))

        self.conn.commit()

    # Adds a user to the students table
    def add_student(self, pitt_id, discord_id):
        cursor = self.conn.cursor()

        cursor.execute("INSERT INTO students VALUES (?, ?)", (pitt_id, discord_id,))
        
        self.conn.commit()

    # Returns the Pitt ID of the user who's Discord ID is given. If not found, returns None
    def get_student_id(self, discord_id):
        cursor = self.conn.cursor()

        pittID = cursor.execute("SELECT pitt_id FROM students WHERE discord_id = (?)", (discord_id,)).fetchone()
        
        return pittID
        
    # Removes the association of a PittID and a Discord ID
    def remove_student_association(self, discord_id):
        cursor = self.conn.cursor()

        cursor.execute("DELETE FROM students WHERE discord_id = (?)", (discord_id,))

        self.conn.commit()

    # Adds a new course into the course table
    def add_semester_course(self, course_number, course_canvas_id, course_name, category_channel_id, recitation_react_message_id, student_role_id, ta_role_id, course_admin):
        cursor = self.conn.cursor()

        cursor.execute("INSERT INTO course VALUES (?, ?, ?, ?, ?, ?, ?, ?)", (course_number, course_canvas_id, course_name, category_channel_id, recitation_react_message_id, student_role_id, ta_role_id, course_admin,))
        
        self.conn.commit()
  
    # Returns a list of all courses
    def get_semester_courses(self, course_admin):
        cursor = self.conn.cursor()

        courseList = cursor.execute("SELECT * FROM course WHERE course_admin = (?)", (course_admin,)).fetchall()

        return courseList

    # Deletes the course table
    def remove_semester_courses(self, course_admin):
        cursor = self.conn.cursor()

        cursor.execute("DELETE FROM course WHERE course_admin = (?)", (course_admin,))
        self.conn.commit()
        
    # Adds a recitation to the recitation table with a FK of its course's Canvas ID
    def add_course_recitation(self, course_canvas_id, course_number, recitation_name, reaction_id, associated_role_id):
        cursor = self.conn.cursor()

        cursor.execute("INSERT INTO recitation VALUES (?, ?, ?, ?, ?)", (course_canvas_id, course_number, recitation_name, reaction_id, associated_role_id,))

        self.conn.commit()

    # Returns a list of all recitations associated with their course's Canvas ID
    def get_course_recitations(self, course_canvas_id):
        cursor = self.conn.cursor()

        recList = cursor.execute("SELECT * FROM recitation WHERE course_canvas_id = (?)", (course_canvas_id,)).fetchall()

        return recList

    # Gets the role that will be assigned to a user when they react correctly to a given message
    def get_role_id(self, reaction_message_id, reaction_id):
        cursor = self.conn.cursor()

        roleID = cursor.execute("SELECT associated_role_id FROM recitation WHERE reaction_id = (?) AND reaction_message_id = (?)", (reaction_id, reaction_message_id,)).fetchone()

        return roleID

    # Add a message's ID and the time it was sent
    def add_message(self, message_id, message_time):
        cursor = self.conn.cursor()

        cursor.execute("INSERT INTO messages VALUES (?, ?)", (message_id, message_time,))
        
        self.conn.commit()

    def get_message_time(self):
        cursor = self.conn.cursor()

        messageList = cursor.execute("SELECT * FROM messages").fetchall()

        return messageList

    def remove_message(self, message_id):
        cursor = self.conn.cursor()

        cursor.execute("DELETE FROM messages WHERE message_time = (?)", (message_id,))
        self.conn.commit()

    def close(self):
        self.conn.close()
